#!/usr/bin/env bash

set -e

declare ZET_PATH="$1"

if [[ ! -d "$ZET_PATH" ]]; then
  nvim --server "$NVIM_SOCKET" --remote-send '<ESC>:lua vim.notify("$ZET_PATH is not a valid directory", "error", {title= "Gitsync"})<CR>'
  exit 1
fi

cd "$ZET_PATH"

_sync() {
  if [[ ! -S "$NVIM_SOCKET" ]]; then
    #
    # If there's no nvim socket
    #
    if ! git rev-parse HEAD >/dev/null 2>&1; then
      return 1
    fi

    if [[ -n "$(git status --porcelain)" ]]; then
      git add .
      git commit -m "Gitsync: $(date +%Y-%m-%d)" -q
      git pull -q
      git push -q
    fi
  else
    #
    # If there's a nvim socket
    #
    if ! git rev-parse HEAD "$ZET_PATH" >/dev/null 2>&1; then
      nvim --server "$NVIM_SOCKET" --remote-send '<ESC>:lua vim.notify("The given path is not a github repo", "error", {title= "Gitsync"})<CR>'
      return 1
    fi

    if [[ -n "$(git status --porcelain)" ]]; then
      nvim --server "$NVIM_SOCKET" --remote-send '<ESC>:lua vim.notify("Saving changes to github...", "warn", {title = "Gitsync"})<CR>'

      git add .
      git commit -m "Gitsync: $(date +%Y-%m-%d)" -q
      git pull -q
      git push -q

      nvim --server "$NVIM_SOCKET" --remote-send '<ESC>:lua vim.notify("Succesfully pushed changes on github...", "info", {title= "Gitsync"})<CR>'
    fi
  fi
}

# run the command on the background
(_sync &) &>/dev/null
