#!/usr/bin/env bash

args="$*"

if [[ ! -S "$NVIM_SOCKET" ]]; then
  nvim --listen "$NVIM_SOCKET" -c "lua require('odas0r.telescope').search_zet({}) ${args}"
else
  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | lua terminal:close()<CR>"
  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | lua require('odas0r.telescope').search_zet({})<CR>i${args}"
fi
