#!/usr/bin/env bash

QUERY="${1:-}"
FLEET_PATH="$2"
PERM_PATH="$3"

if [[ -z $FLEET_PATH ]] || [[ -z "$PERM_PATH" ]]; then
  echo "error: invalid args on script 'query'"
  exit 1
fi

rg --column --line-number --no-heading --color=always --smart-case "$QUERY" "$FLEET_PATH" "$PERM_PATH"
